### ISSUE TITLE
The 'ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8"' distribution was not found and is required by ruamel.yaml

### ISSUE THREAD

**Issue by lightsquared** [chrisjsewell/ipypublish#102]
# Bug Report

## Describe the bug

Attempt to publish a Jupyter Notebook to pdf and get the following error:

Run Failed: The 'ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8"' distribution was not found and is required by ruamel.yaml

## To Reproduce

1. Clean install of miniconda (Aug 25, 2019)
2. conda env create -f environment.yml
3. nbpublish -pdf -lb -f latex_ipypublish_nocode philadelphia_refinery.ipynb

## Minimal Notebook Example

[ipypublish_example.txt](https://github.com/chrisjsewell/ipypublish/files/3538390/ipypublish_example.txt)

## Expected Behaviour

Generate a pdf of the ipynb file.

## Runtime Information

(please complete the following information)

- IPyPublish: [0.10.8]
- Python: [3.7.4]
- OS: [OSX 10.14.6]
- Pandoc: [2.2.3.2]

- texlive: [1.35]
- latexmk: [4.65]

- ruamel [1.0]
-ruamel.yml [0.16.5]

## Logging

(philadelphia_refinery) Shonns-MacBook-Pro:4_analysis skmcneill$ nbpublish -pdf -lb -f latex_ipypublish_nocode philadelphia_refinery.ipynb
INFO:ipypublish:started ipypublish v0.10.8 at Sun Aug 25 11:41:47 2019
INFO:ipypublish:logging to: /Users/skmcneill/Documents/github/philadelphia_refinery/4_analysis/converted/philadelphia_refinery.nbpub.log
INFO:ipypublish:running for ipynb(s) at: philadelphia_refinery.ipynb
INFO:ipypublish:with conversion configuration: latex_ipypublish_nocode
INFO:nbmerge:Reading notebook
INFO:ipypublish:finding conversion configuration: latex_ipypublish_nocode
INFO:ipypublish:loading conversion configuration
INFO:ipypublish:creating exporter
INFO:ipypublish:creating template and loading filters
INFO:ipypublish:creating process configuration
INFO:ipypublish:running nbconvert
INFO:root:adding ipub defaults to notebook
INFO:root:splitting outputs into separate cells
INFO:resolve_links:resolving external file paths in ipub metadata to: philadelphia_refinery.ipynb
INFO:captions:extracting caption cells
ERROR:nbpublish:Run Failed: The 'ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8"' distribution was not found and is required by ruamel.yaml

## Conda Environment File

[philadelphia_refinery.txt](https://github.com/chrisjsewell/ipypublish/files/3538398/philadelphia_refinery.txt)

**Comment by chrisjsewell** [comment]
Thanks for the report @lightsquared. This occurs because in `ruamel.yaml v0.16` they "split off C source that generates .so file to ruamel.yaml.clib". Therefore, if you either `conda install "ruamel.yaml<0.16"` or `pip install ruamel.yaml.clib` (since it is not currently available on conda), this should fix the issue.

I have logged an issue upstream to see about fixing this: conda-forge/ruamel.yaml-feedstock#116

**Comment by chrisjsewell** [comment]
For now, I have pinned `ruamel.yaml<0.16` in the conda distribution (`0.10.8-pyXX_1`)

**Comment by lightsquared** [comment]
The pip install ruamel.yaml.clib fixed the issue.  Thanks for the quick reply.  Your library completely changes the way I use jupyter notebook.  Thanks so much.
