### ISSUE TITLE
Allow additional custom stylesheet to be linked in slide output

### ISSUE THREAD

**Issue by phelps-sg** [chrisjsewell/ipypublish#121]
It would be useful to be able to specify an additional custom stylesheet when producing html slideshows.  This could be used, e.g. to allow a corporate logo to be displayed on each slide.

**Comment by chrisjsewell** [comment]
Yep sounds quite possible. Your PR (#122) appears to have some issues with conflicts at present though :)

**Comment by phelps-sg** [comment]
I've resolved conflicts in PR #122
