### ISSUE TITLE
pathlib dependency?

### ISSUE THREAD

**Issue by danmackinlay** [chrisjsewell/ipypublish#15]
I notice that pathlib 1.0.1 is given as a dependency. [pathlib](https://pypi.python.org/pypi/pathlib/) is is maintenance-only mode and no longer tracks python 3's pathlib. The preferred backbork of pathib to python 2 is [pathlib2](https://pypi.python.org/pypi/pathlib2/). Is there a particular reason to prefer pathlib, or should I prepare a patch

**Comment by chrisjsewell** [comment]
nope no reason that I recall, so go ahead :)

**Comment by chrisjsewell** [comment]
Was actually already setup for pathlib2, just put pathlib in requirements by accident fcc0ecf0ee0f4f53dde90555c42238516bb1d84c
