### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by danmackinlay** [chrisjsewell/ipypublish#18]
There are a lot of trailing whitespace and long lines in the code in violation of PEP8.

This is bad because it confuses the crap out of my IDE, which has automatic PEP8 linking via Flake8, and the trailing whitespace makes for noisy patches with lots of trivial whitespace changes.

I am happy to submit a PR which fixes all whitespace issues, but I'll have to wait until @chrisjsewell goes to  sleep, since the patch won't apply at the current rate of updates ;-)

**Comment by chrisjsewell** [comment]
Yeh go for it, I'm a bit lazy with that side of things! should really put something like that in my IDE to keep me on the straight and narrow

**Comment by danmackinlay** [comment]
😁 Will do - have to go write papers first for a while ;-)

**Comment by chrisjsewell** [comment]
Removed all trailing whitespaces, reformatted code base with pycharm and linked repo to codacy for integrated code style checking: https://www.codacy.com/app/chrisj_sewell/ipypublish 😁
