### ISSUE TITLE
Document how you actually registers a bespoke pluginesque output formatter

### ISSUE THREAD

**Issue by danmackinlay** [chrisjsewell/ipypublish#20]
The documentation mentions the ability to create bespoke output plugins, but not how to register them with the output plugin system. This is presumably though the ``ipypublish.scripts.export_plugins.add_directory`` function, but that should probably be mentioned.

**Comment by chrisjsewell** [comment]
Yeh absolutely, thats on the todo list. Essentially I've just copied the approach which I implemented in my other package: https://github.com/chrisjsewell/jsonextended#creating-and-loading-plugins, whereby it just goes through the folder, loads the modules and checks for the correct interface spec (with getattr).

I guess there is fancier methods, like having yaml spec files, but i thought this was the most lightweight approach

**Comment by chrisjsewell** [comment]
Is this at all intelligible now? https://github.com/chrisjsewell/ipypublish#creating-a-bespoke-converter
I've added a few lines to the start of nbpresent and nbpublish, to read in plugins from an (optional) folder in the current working directory. I imagine that could be helpful for people running it from the command line (rather than from the API)

**Comment by angeloklin** [comment]
Hello Chris,
  I tried the process base on the current documentation of the GitHub README, but could not make it work, that I had to stop as I run out of time to investigate it further.

  Maybe a `how to` with step-by-step instructions would be helpful.

  Still in `documentation` but on another topic: the `titlepage` is missing a `}`
```
{
  "latex_doc": {
    "titlepage": {
      "author": "Authors Name",
      "email": "authors@email.com",
      "supervisors": [
        "First Supervisor",
        "Second Supervisor"
      ],
      "title": "Main-Title",
      "subtitle": "Sub-Title",
      "tagline": "A tagline for the report.",
      "institution": [
        "Institution1",
        "Institution2"
      ],
      "logo": "path/to/logo_example.png"
    } <<<<<<<<<< missing close bracket to close titlepage
  }
}
```
