### ISSUE TITLE
Simpler plugin registry

### ISSUE THREAD

**Issue by danmackinlay** [chrisjsewell/ipypublish#21]
(Sorry for the barrage of issues. Hopefully they will encourage me to submit PRs implementing the good ones)

Looking at the plugin system here, it seems to be solving a similar problem to many other python projects (markdown, Docutils, Django...) where plugins are defined. Those systems use a "register" pattern, where it's the plugins' job to announce their existence to the app on import. This requires a  lot less code; you just keep a dictionary somewhere full of plugin names and don't worry about file paths. This would probably be simpler than the "add_directory" thing and avoid having to mess around with importlib in a python2/3-friendly way, which is painful.

**Comment by chrisjsewell** [comment]
Does this mean you would have to specifically load all the plugins? I thought it was quite nice being able to just point towards a directory and have the program load them all up. But yeh, I'm no expert on plugin systems and don't have the time to look into it, so happy if you want to submit a PR for me to have a look at how it would work.

I have importlib working in a python2/3-friendly way already don't I, is there any issues?
