### ISSUE TITLE
add text label

### ISSUE THREAD

**Issue by chrisjsewell** [chrisjsewell/ipypublish#30]
For output text/stream text/error messages/tracebacks, with option to color by code language, wrap in box, maybe different color to code

Make sure its added to latex, html and slides

**Comment by angeloklin** [comment]
Hello Chris,
  A bit of a catch, that you might take in steps.
  Remember I said I have something like:
```
for col in columns:
  col.describe()  # << Text output
  col.plot()      # << graphic output
```

  Keep in mind that there are both text and image in the output. Worse: because there is a loop, they alternate. I haven't checked the actual `.ipynb` to see how `jupyter` separate the multiple types in one `output`. Maybe it does like multiple mime types in emails.
  It is more a reminder of a use case, as you sure know the internals.

**Comment by chrisjsewell** [comment]
So from what I understand here, your concern is about the order of the outputs? I just tried outputting a [plot, text, table, text, plot] like this:

```python
plt.scatter(np.random.rand(10), np.random.rand(10), 
            label='data label')
plt.show()
print('after 1st plot')
from IPython.display import display
display(pd.DataFrame(np.random.rand(3,4),columns=['a','b','c','d']))
print('after table')
plt.scatter(np.random.rand(10), np.random.rand(10), 
            label='data label');
```

and they output in the correct order in the Jupyter notebook. Then if I add the metadata:

```json
  "latex_doc": {
    "figure": {
      "placement": "H"
    },
    "table": {
      "placement": "H"
    }
```
and run `nbpublish -pdf example/notebooks/Example.ipynb`, you get the plots and table in the right order (obviously not the text yet). So it should be fine with the text as well.

**Comment by chrisjsewell** [comment]
Obviously, in this approach, you cant specify a caption/label for each individual plot. I don't know if you've already thought of this but one suggestion would be to use `matplotlib subplots`. Something like this:

```python
fig, axes = plt.subplots(len(columns))
for ax, data in zip(axes,all_data):
    ax.plot(data.x, data.y)
    ax.set_title(data.describe)
```

**Comment by chrisjsewell** [comment]
Lastly, I've had an alternate thought on the *draft* converter: What I could do is create a `nb_ipypublish` notebook->notebook converter, which would output a new notebook, exactly the same as the input notebook, but with *default* settings for all metadata tags (if not already present), i.e. if a cell in the input notebook had no metadata:

```json
{}
```

the same cell in the 'new' notebook would have metadata:

```json
  "latex_doc": {
    "figure": {
      "placement": "H"
    },
    "equation": true,
    "text": true,
    "table": {
      "placement": "H"
    }
  }
```

That means, it would achieve the same outcome, but then its easier to start 'finessing' the pdf output, later down the line. Does that seem reasonable?

**Comment by chrisjsewell** [comment]
and lastly lastly, I was thinking, rather than a `step-by-step how to`, it might be easy to make a little 'follow along' youtube screen capture video.

**Comment by angeloklin** [comment]
Hello Chris,
  Interesting ideas.
  The initial alert was just a reminder that the output can have a mixture of formats. If both the notebook and the templates are already working, then great.

  I commend you for trying to solve all the problems with some creative ideas, but my poor man alternative would be to include latex syntax for the captions if I decide to use any at all. As a data scientist, I try to make the visualisations speak for themselves and have titles, legends, etc all in the actual chart. Formal and academic texts have their own standards. Maybe the message is to not try to overcomplicate things. It might come back to haunt or harm you in the future. If needed by yourself or someone else, it will come up.

  In my current and specific case, I just want to read the data I was given and report back on the data quality. So it is supposed to be just a report that might be used just once. Well, it could be a regular thing, which lowers the bar even more. It is just targeted to be a consumable.

  I don't want to discourage you, just being open in my opinion to keep it simple. Entirely up to you to take into account or not. Your code has been and will be very helpful. I could not find anything else aside from creating from scratch. So thanks again.

  As for the visual tutorial on youTube, sounds better, as people can check it out if they want, but would not make the document page "heavier". But depending on the task, some text is also good. The video you might have to pause and rewind, which is complex than simply reading the instructions again.

Cheers

**Comment by chrisjsewell** [comment]
Right job done, added the text tag and [documentation](https://github.com/chrisjsewell/ipypublish#cell-tags) about it. 

I've created a simple [MetaDefaults preprocessor](https://github.com/chrisjsewell/ipypublish/blob/master/ipypublish/preprocessors/latex_doc_defaults.py) to apply (arbitrary) default notebook/cell level meta-tag defaults to a copy of the input notebook. This actually make things a lot simpler rather than complicated because now, if you look in the [plugin library](https://github.com/chrisjsewell/ipypublish/tree/master/ipypublish/export_plugins) you'll see a load more ending `_all` and `_nocode`. The one your after is [latex_ipypublish_nocode](https://github.com/chrisjsewell/ipypublish/blob/master/ipypublish/export_plugins/latex_ipypublish_nocode.py)

All I've done here is just added MetaDefaults to the existing plugins, with some different defaults.  a) this means they are all using the same template (so a lot easier to maintain/improve) and b) this means that it would be really easy now for you to make a new plugin (if you needed different defaults) by copy/pasting `latex_ipypublish_nocode` and just making changes to `cell_defaults` and/or `nb_defaults`.

**Comment by angeloklin** [comment]
Hello Chris,

  You have been busy. Well Done.
  I will give it a go and will let you know.
  On a side note, Yesterday occurred to me that I could go around the text display using a table. In some cases, it would be ok or even better; in others maybe not so much, but now you offer a solution for that as well. Thanks!

  Quick question: Is there a new version (0.4.2 or 0.4.5) to incorporate the new plugins? If not how do I register the new ones?

Thanks

**Comment by angeloklin** [comment]
Hello Chris,
  I am trying to run the `latex_ipypublish_nocode` but still getting errors.
  I downloaded the fresh versions from GitHub and created the `ipypublish_plugins` directory but still no luck.

```
$ ls -l 
-rw-r--r--  1 angeloklin  staff   11009 19 Jul 18:34 10_Download.ipynb
-rw-r--r--  1 angeloklin  staff  950500 20 Jul 18:43 20-EDA-tbl_FA_360_Full.ipynb
-rw-r--r--@ 1 angeloklin  staff  859491 19 Jul 10:07 Example.ipynb
-rw-r--r--  1 angeloklin  staff  130510 20 Jul 18:47 Untitled.ipynb
drwxr-xr-x@ 7 angeloklin  staff     238 18 Jul 07:53 example
drwxr-xr-x@ 5 angeloklin  staff     170 21 Jul 09:32 ipypublish_plugins

$ ls -l ipypublish_plugins/
-rwxr-xr-x@ 1 angeloklin  staff    83 20 Jul 14:55 __init__.py
-rwxr-xr-x@ 1 angeloklin  staff  1830 20 Jul 14:55 latex_ipypublish_all.py
-rwxr-xr-x@ 1 angeloklin  staff  1822 20 Jul 14:55 latex_ipypublish_nocode.py

$ nbpublish -f latex_ipypublish_nocode -pdf Untitled.ipynb

error: argument -f/--outformat: invalid choice: 'latex_ipypublish_nocode' 
(choose from 'slides_ipypublish', 'html_standard', 'latex_standard_article', 
'html_ipypublish', 'slides_standard', 'latex_ipypublish_main')
usage: nbpublish [-h] [-f str] [-o str] [-d] [-i str] [-pdf] [-ptemp] [-pbug]
                 [-log {debug,info,warning,error}]
                 filepath

. . .

Available Output Formats
------------------------
- html_ipypublish:
  html in standard nbconvert format, but with 
  - a table of contents 
  - toggle buttons for showing/hiding code & output cells
ef{})onverts or removes (if no converter) latex tags (like \cite{abc},     ## <<<< some garble here?
  
. . .

```

**Comment by chrisjsewell** [comment]
Hey sorry for the delay, just wanted to finish this section on [embedding 3d graphics](https://github.com/chrisjsewell/ipypublish#embedding-interactive-html) before updating the version. `ipypublish 0.5.0` ready for pip install! 

There was actually a little bug in the earlier plugin load code, but I've fixed that and explicitly added the [ipypublish_plugins](https://github.com/chrisjsewell/ipypublish/tree/master/ipypublish_plugins) in the repo (with an example plugin), and included it in the integration testing. So it should work fine now and include your plugin in the 'Available Output Formats' section of `nbpresent -h`.

**Comment by angeloklin** [comment]
That is efficiency (and good timing).
Will check and test.
Thanks

**Comment by chrisjsewell** [comment]
Ta

**Comment by angeloklin** [comment]
OK, first run with 0.5.0.

  Started by testing the `Untitled.ipynb` with:

```
$ rm -rf converted; nbpublish -f latex_ipypublish_nocode -pdf Untitled.ipynb
```
  All goes as expected on a first glance. Did not investigate further, but looks just fine.

  Then I tried with my project file. I run for the analysis of a file with 191 columns, to which I am testing with the first 12 only.

  Running just the first cells, of goes all OK.

  I got some error messages, so I reset the kernel and run all but the cell that goes over the columns. I have added the meta tags for the notebook and nothing else.
  The return error from the run was:

```
$ rm -rf converted; nbpublish -f latex_ipypublish_nocode -pdf --pdf-debug 20-EDA-tbl_FA_360_Full.ipynb

. . .
Traceback (most recent call last):
  File "/Users/angeloklin/anaconda2/bin/nbpublish", line 138, in <module>
    nbpublish(filepath, **options)   
  File "/Users/angeloklin/anaconda2/bin/nbpublish", line 64, in nbpublish
    create_pdf=create_pdf, pdf_in_temp=pdf_in_temp, pdf_debug=pdf_debug) 
  File "/Users/angeloklin/anaconda2/lib/python2.7/site-packages/ipypublish/main.py", line 154, in publish
    raise RuntimeError('the pdf export failed, try running with pdf_debug=True')
RuntimeError: the pdf export failed, try running with pdf_debug=True
```

  From the log, there are a few lines that give some info:
```
INFO:pdfexport:latexmk: *geometry* driver: auto-detecting
INFO:pdfexport:latexmk: *geometry* detected driver: pdftex
INFO:pdfexport:latexmk: <20-EDA-tbl_FA_360_Full_files/image001.png, id=7, 45.92157pt x 45.92157pt>
INFO:pdfexport:latexmk: <use 20-EDA-tbl_FA_360_Full_files/image001.png>
INFO:pdfexport:latexmk: Overfull \hbox (57.92407pt too wide) in paragraph at lines 383--384
INFO:pdfexport:latexmk: [][][]\T1/ppl/m/n/14.4 angelo.klin@immersive.com.au[][]
INFO:pdfexport:latexmk: (/usr/local/texlive/2017/texmf-dist/tex/latex/psnfss/ot1ppl.fd)
```

```
INFO:pdfexport:latexmk: Overfull \vbox (12.0pt too high) has occurred while \output is active [2]
INFO:pdfexport:latexmk: [3]
INFO:pdfexport:latexmk: ! TeX capacity exceeded, sorry [main memory size=5000000].
INFO:pdfexport:latexmk: <argument> ... =\vbox {\unvcopy \mdf@splitbox@one
INFO:pdfexport:latexmk: }\splitmaxdepth \z@ \split...
INFO:pdfexport:latexmk: l.770 \end{lstlisting}
INFO:pdfexport:latexmk: 
INFO:pdfexport:latexmk: !  ==> Fatal error occurred, no output PDF file produced!
INFO:pdfexport:latexmk: Transcript written on 20-EDA-tbl_FA_360_Full.log.
INFO:pdfexport:latexmk: Collected error summary (may duplicate other messages):
INFO:pdfexport:latexmk: pdflatex: Command for 'pdflatex' gave return code 1
INFO:pdfexport:latexmk: Refer to '20-EDA-tbl_FA_360_Full.log' for details
INFO:pdfexport:latexmk: Latexmk: Use the -f option to force complete processing,
INFO:pdfexport:latexmk: unless error was exceeding maximum runs of latex/pdflatex.
INFO:pdfexport:latexmk: === TeX engine is 'pdfTeX'
INFO:pdfexport:latexmk: Latexmk: Errors, so I did not complete making targets
ERROR:pdfexport:pdf conversion failed: Try running with pdf_debug=True
ERROR:main:pdf export returned false, try running with pdf_debug=True
```

to be continued. . .

**Comment by angeloklin** [comment]
. . .
  I then decided to run cell by cell and see which one starts the error.

  There is one cell with a large output that is the first one to force the error:

```
Overfull \vbox (12.0pt too high) has occurred while \output is active []

[2] [3] [4]
Package mdframed Info: Not enough space on this page on input line 770.
! TeX capacity exceeded, sorry [main memory size=5000000].
<argument> ... =\vbox {\unvcopy \mdf@splitbox@one 
                                                  }\splitmaxdepth \z@ \split...
l.770 \end{lstlisting}
                      
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.

 
Here is how much of TeX's memory you used:
 40061 strings out of 492995
 774506 string characters out of 6132705
 5000000 words of memory out of 5000000
 42864 multiletter control sequences out of 15000+600000
 557718 words of font info for 92 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 73i,19n,124p,10492b,2248s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```

  The code:
```
for i, c in enumerate(df.columns):
    print('%3d-%-44s (%-8s/%-14s): %s' % (i, c, col_def[i][1], df[c].dtype, df[c][0]))
```

  The output:
```
  0-REQUEST_ID                                   (int     /object        ): 3887344
  1-REQUEST_EXTERNAL_WO_NUMBER                   (nvarchar/object        ): nan
  2-REQUEST_TYPE                                 (nvarchar/object        ): PM - Electrical Systems
  3-REQUEST_SUBTYPE                              (nvarchar/object        ): Standard PM
. . .
187-EXTERNALCOSTCENTER                           (nvarchar/object        ): nan
188-PROCEDURE_TYPE                               (nvarchar/object        ): nan
189-LAST_UPDATE_DATE_GMT                         (datetime/datetime64[ns]): 2017-06-06 06:07:55
190-AsOn_Date                                    (datetime/datetime64[ns]): 2017-07-20 00:03:56
```

  Nothing special, but a large output.

  If I re-run but skipping the output, the error goes away. Looks like it is a memory issue here.

  After going cell by cell, even the one with the analysis runs OK for 12 variables, mixing text and charts for each variable.
  Also looks like that if each portion or block, if not too big, works just fine.

  Very promising and maybe 99%. The point is it runs successfuly.

**Comment by angeloklin** [comment]
OK,
  Looking at the fine grain now.
  How to and where to change the configuration to influence the `.tex` to:
  - change margins
  - change font size

  I got the reference to the `"format": {}`, but what is the syntax? Here is where some examples would be great. I looked link about the Listing Tex package but how one translates to the other?

  I tried this:
```
  "latex_doc": {
    "text": {
      "format": {
        "basicstyle": "\tiny"
      },
      "asfloat": true,
      "caption": "",
      "label": "code:example_sym",
      "widefigure": false,
      "placement": "H"
    }
```

  And no luck. So I am trying all the combinations to see if/what works. An example would give some hints on that.

**Comment by angeloklin** [comment]
This one works:
```
    "latex_doc": {
     "text": {
      "format": {
       "basicstyle": "\\small"
      },
     }
```

**Comment by chrisjsewell** [comment]
brilliant, I knew adding that format tag would be useful :), yes, for json, you have to use \\ in place of any \

**Comment by chrisjsewell** [comment]
There's basically just a little function that turns this `{"a":1,"c":3}` into this `\begin{lstlisting}[a=1,c=3]`

**Comment by chrisjsewell** [comment]
I guess you could just set `breaklines=false` to avoid it failing

**Comment by chrisjsewell** [comment]
ok so yeh, I think the main issue was that I had `postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space}`, which creates a red arrow to indicate a line continuation and looks really nice for code cells ([see here](https://tex.stackexchange.com/a/116572/107738)). But evidently this is a memory drain for large amounts of line wrapping. So, I'm now setting the default for stream text (i.e. from `print` commands) to:

`language={},postbreak={},numbers=none,xrightmargin=7pt,breakindent=0pt,aboveskip=5pt,belowskip=5pt`

Let me know if that seems good or you work out a nicer default, ta

**Comment by chrisjsewell** [comment]
in case I forget to mention, because of this commit ff1b93aef954eb789f82be5d4d636734d5beed06, you will have to make a change to 2 of the code lines of your custom plugin, when the next version is released, for it to still work:
```python
from ipypublish.preprocessors.latex_doc import LatexDocLinks
```
to
```python
from ipypublish.preprocessors.latex_doc_links import LatexDocLinks
from ipypublish.preprocessors.latex_doc_captions import LatexCaptions
```
and
```
          'Exporter.preprocessors':[LatexDocLinks]}
```
to
```
          'Exporter.preprocessors':[LatexDocLinks,LatexCaptions]}
```

**Comment by angeloklin** [comment]
Hello Chris,

  I hope you had a nice weekend. Seems you have been busy.

  I spent some more time trying to get my head around producing my report. I managed to get the content almost as good. But I am now back to give it a format, to which I am relying on `ipypublish` as it is the best alternative around.

  I put together a down version of my notebook, to give you an idea. In essence, it is simple, but not as much when it comes to the output.
  The catch is the loop with multiple formats. You have solved it with your new release, but I still have a few requests if you will:
  - You might have noticed that if you just put a pandas dataframe at the end of a cell it prints very nicely, but if it is inside a loop or an if, then it does not work. You have then to use it with print, which transforms into a string. One option to keep the visual is to use `display()` instead of `print()`.
  - The other thing is to manage to for a page break (`\newpage`).

  In both cases I not sure if I could create a preprocessor or an extension to manipulate the `"text/markdown": ["\\newpage"]` and `"text/html": [". . ."]`.

  There are catches on those too:
  - `display()` produces both `text/html` and `text/plain`
  - using metadata for figures/tables/caption makes it repetitive unless there would be a way to inject content into the metadata via code;
  - the forced markdown, such `# Title`, could have to be checked to be part of the TOC.

  Some food for thought unless you already have a solution that I cannot see from the bottom up. (I still don't quite get the big picture).

  Below is some code for testing.

Thanks and have a good day.
PS: Feel free to move to another ticket if this is getting out of topic or too long.

## `Test.ipynb`
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "init_cell": true,
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "# load libraries\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "df = pd.DataFrame({'A': [np.random.randint(0, 100) for i in range(1000)],\n",
    "                   'B': [np.random.randint(0, 100) for i in range(1000)],\n",
    "                   'C': [np.random.randint(0, 100) for i in range(1000)]})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "from IPython.display import display\n",
    "from IPython.display import display_latex\n",
    "from IPython.display import display_markdown\n",
    "from IPython.display import Latex\n",
    "# from IPython.display import Markdown"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "def print_describe(var):\n",
    "    \n",
    "    kind = var.dtype.name\n",
    "    data = []\n",
    "    value = []\n",
    "\n",
    "    # Variable name\n",
    "    data.append('Variable')\n",
    "    value.append(var.name)\n",
    "    # Data type\n",
    "    data.append('Data type')\n",
    "    value.append(var.dtype)\n",
    "    # Data type name\n",
    "    data.append('Data type name')\n",
    "    value.append(var.dtype.name)\n",
    "    # content\n",
    "    data.append('Not NULL')\n",
    "    value.append(var.count())\n",
    "    # NULLs\n",
    "    data.append('NULLs')\n",
    "    value.append(len(var) - var.count())\n",
    "\n",
    "    df = pd.DataFrame({'Data': data, 'Value': value},\n",
    "                      columns=['Data', 'Value'])\n",
    "    display(df)\n",
    "#     display(df.to_string(index=False))\n",
    "#     display(df.to_latex(index=False))\n",
    "#     display_latex(df.to_latex(index=False))\n",
    "#     display(Latex(df.to_latex(index=False)))\n",
    "\n",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "def print_top_bottom(var):\n",
    "    \n",
    "    vc = var.value_counts()\n",
    "    if len(vc) == 0:\n",
    "        return\n",
    "\n",
    "    kind = var.dtype.name\n",
    "    n = min(len(vc), 5)\n",
    "    desc_n = range(n)\n",
    "    desc_k = list(vc.keys())[:n]\n",
    "    desc_v = list(vc)[:n]\n",
    "\n",
    "    vc = var.value_counts(ascending=True)\n",
    "    asc_n = range(len(vc), 0, -1)[:n]\n",
    "    asc_k = list(vc.keys())[:n]\n",
    "    asc_v = list(vc)[:n]\n",
    "\n",
    "    df = pd.DataFrame({'TOP: Idx': desc_n, 'T.Data': desc_k, 'T.Count': desc_v,\n",
    "                       'BOTTOM: Idx': asc_n, 'B.Data': asc_k, 'B.Count': asc_v},\n",
    "                      columns=['TOP: Idx', 'T.Data', 'T.Count', \n",
    "                               'BOTTOM: Idx', 'B.Data', 'B.Count'])\n",
    "    display(df)\n",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "def print_bar_chart(var):\n",
    "\n",
    "    var.plot(figsize=(15, 5))\n",
    "    plt.title('Column %s' % var.name)\n",
    "    plt.show()\n",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "latex_doc": {
     "ignore": true
    }
   },
   "outputs": [],
   "source": [
    "def EDA_univariate(var):\n",
    "    \n",
    "    display_markdown('## Describe', raw=True)\n",
    "    print_describe(var)\n",
    "\n",
    "    display_markdown('## Most/Least common', raw=True)\n",
    "    print_top_bottom(var)\n",
    "\n",
    "    display_markdown('## Chart', raw=True)\n",
    "    print_bar_chart(var)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Full Report\n",
    "For each column will have:\n",
    "\n",
    "- Title (markdown)  \n",
    "- Details (pandas table)  \n",
    "- Most/Least common (pandas table)  \n",
    "- Chart (image/matplotlib)  \n",
    "- **LaTeX** (`\\newpage`)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "latex_doc": {
     "figure": {
      "caption": "Figure caption.",
      "label": "figure:flabel",
      "placement": "H"
     },
     "table": {
      "alternate": "gray!20",
      "caption": "An example of a table created with pandas dataframe.",
      "label": "table:example",
      "placement": "H"
     },
     "text": {
      "asfloat": true,
      "caption": "",
      "format": {
       "basicstyle": "\\small"
      },
      "label": "text:example_text",
      "placement": "H",
      "widefigure": false
     }
    },
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "for col_name in df.columns[0:3]:\n",
    "    display_markdown('# Column: %s' % col_name, raw=True)\n",
    "\n",
    "    col = df[col_name]\n",
    "    kind = col.dtype.name\n",
    "\n",
    "    EDA_univariate(col)\n",
    "    \n",
    "    display_markdown('\\\\newpage', raw=True)\n",
    "    display_latex('\\\\newpage', raw=True)"
   ]
  }
 ],
 "metadata": {
  "celltoolbar": "Edit Metadata",
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  },
  "latex_doc": {
   "listcode": false,
   "listfigures": true,
   "listtables": true,
   "titlepage": {
    "author": "Angelo Klin",
    "email": "professional@angeloklin.com",
    "institution": [
     "Katra"
    ],
    "subtitle": "360",
    "supervisors": [
     "The Boss"
    ],
    "tagline": "A tagline for the report.",
    "title": "Data Source"
   },
   "toc": true
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by chrisjsewell** [comment]
Yes thanks, same to you :)

So firstly, since you are not using `from ipypublish.scripts.ipynb_latex_setup import *`, you need to specifically setup pandas to output latex:

```python
pd.set_option('display.latex.repr',True)
pd.set_option('display.latex.longtable',False)
pd.set_option('display.latex.escape',False)
```
The nbconvert only renders the highest priority data type per data item (e.g. for a latex that means data/latex, whereas for html that means data/html), so it doesn't matter if the if there are multiple types per output.

Secondly, the aim of ipypublish (at least as initially intended and what I am using it for) is to create *man in the loop* documents:

- you write some text in a markdown cells
- create a **single** figure/table/equation per code cell
- mark that up with a caption,label,... 
- refer to and write about it in a markdown cell 
- and repeat

In doing so you write your entire article in one place, rather than having the text in one place and the code/images in another. When you say "using metadata for figures/tables/caption makes it repetitive", that it because you want all your figures/tables to have standardized captions etc, which is not the case if you are writing a scientific article. I need to define exactly how each one of mine look individually.

What you appear to be after is *fully automated* document creation,  Really the ideal solution for this would be to actually write code which created the whole .ipynb file without you ever opening one up, and hence create automated metadata. But, if you don't want to go down this route,  what you need is a preprocessor to split up each output into a separate cell:

1. loop through each output in the cell's "outputs" list
2. if the output.data contain "text/markdown" create a markdowncell with its "source" field equal to this
3. else create a cell with metadata equal to the original cell

I use this splitting of cells approach for instance [here](https://github.com/chrisjsewell/ipypublish/blob/master/ipypublish/preprocessors/slides_from_markdown.py).

Lastly, if you look at the .ipynb after it has run, you will see that each output has its own metadata:

```python
"outputs":[
     {
     "data": {
      "text/markdown": [
       "## Most/Least common"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    ]
```

However I don't know how to go about populating this and its not within the scope of what I am trying to achieve.

**Comment by angeloklin** [comment]
Hello Chris,
  Thanks for your reply, the comments and suggestions.
  I will have a look in details tomorrow at the office.
  To address your comment on automation, that is not what I am looking for as a real end-to-end solution. I still have to run the notebook and analyse it. But at the early stage of data cleaning, it is repetitive. In this instance, it is a univariate analysis, so I need to check each column. So it is more a report rather than a paper or article. The real analysis will come later after I can trust the data. But then there will be another document.
  I think you are tackling a very big problem, as the jupyter notebook environment is not that accessible for this kind of interaction. If you search on the internet it is very hard to find something, and the alternative is to mess with Jinja, as if Tex were not complex already.
  Rmarkdown and Knitr are not a breeze but work much better.
  As I write, I might consider getting out of the ipynb and go just python and then do some processing or my own. Maybe I can force the output to be all markdown/latex or some other thing that can be translated directly to pdf using latex, pandoc or something. Things I will have to consider.

Thanks!

**Comment by angeloklin** [comment]
FYI:

[R Markdown Gallery](http://rmarkdown.rstudio.com/gallery.html)
[R Markdown Engines](http://rmarkdown.rstudio.com/authoring_knitr_engines.html)
[R Markdown Overview](http://rmarkdown.rstudio.com/lesson-1.html)

**Comment by angeloklin** [comment]
Hello Chris,
  After considering going back to the `RStudio` with `RMarkdown` and `Python`, I turned to creating a `LaTeX` file from the data I am reading/creating.
  I was between `Markdown` and `LaTeX`, but decided for `LaTeX`. `Markdown` would probably be easier and I could use `pandoc` to convert, but you inspired me to create a better output.
  I also took the opportunity to learn/play with `LaTeX` as I barely touched it in the past.
  The end result is that in about a day, I got the end result.

  Thanks for your support.
  Looking forward to see `ipypublish` v1.0.1. As I said, I could not find many and good tools to get things out of `Jupyter` and `ipypublish` does it quite well. It has the potencial to be a must have tool.

All the best.
PS. I believe you can close this ticket.

**Comment by chrisjsewell** [comment]
Hey @angeloklin  just a final follow up:

1. I added a 'mkdown' tag so that text/markdown will be rendered the same as other outputs (no creating new cells or anything). This will work exactly the same as text in markdown cells, so titles, newpages etc will all be handled fine.
2. looking at the `display` function, I see that it actually has a `metadata` option, to add metadata for that specific output. So all you actually have to do is create a preprocessor which splits outputs into separate cells using the original cell metadata or, if present, the output level metadata. I have added a seperate issue here to do this #35 i.e.

```python
display(df1, metadata={"ipub":{"table":"caption":"my caption"}})
display(df2, metadata={"ipub":{"table":"caption":"my other caption"}})
```

So I think that would basically solve your use case? Thanks again for your input and please let me know if you have any other ideas

PS: Yeh I've seen about RMarkdown, looks very much like blatant plagiarism to me ;)

**Comment by chrisjsewell** [comment]
FYI If you run https://github.com/chrisjsewell/ipypublish/blob/master/example/notebooks/MultiOutput_Example.ipynb with ipypublish v0.6.1, this should be exactly what you were after with output level metadata.

I've also added further documentation [here](https://github.com/chrisjsewell/ipypublish#the-ipypublish-defaults) and [here](https://github.com/chrisjsewell/ipypublish#metadata-tags)

**Comment by angeloklin** [comment]
Hello Chris,
  Heading very fast to a 1.0.1. Well done.
  You now have done the complete set (text/code/markdow/table/figure).
  Just awesome. It does solve my use case. Thanks a lot.
  The examples you sent above are very good and probably should get a place in the documentation as well. The example also helps.

PS: You might be right about RMarkdown.  :)

**Comment by chrisjsewell** [comment]
FYI something you may be interested in: https://github.com/chrisjsewell/ipypublish#object-output-formats
