### ISSUE TITLE
Multiple output formats and passing `metadata` to the `display` function

### ISSUE THREAD

**Issue by angeloklin** [chrisjsewell/ipypublish#37]
Hello Chris,
  I saw some of the updates in the documentation. Good to have more info.

  I am having some problems and maybe it is documented but I could not make it work still.

  Below are some text and a test notebook to show what I am doing.

# Problem
- This is more related with LaTeX but even using `"placement": "H"` does not force the elements to appear in the proper sequence. This could be related to the processing of an unordered list or dictionary.
- There is no `caption` for the table.

### There should be a ToC
- ToC is NOT present with the default style.
- ToC IS present with the `-f latex_ipypublish_nocode`
- The ToC should include tables
- The ToC should include figures

Thanks and Regards,
Angelo 
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data quality\n",
    "High-quality data needs to pass a set of quality criteria. Those include:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# libraries\n",
    "import re\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "pd.set_option('display.precision', 10)\n",
    "\n",
    "from IPython.display import display\n",
    "from IPython.display import Markdown\n",
    "\n",
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt\n",
    "plt.ioff()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def to_markdown(df):\n",
    "    \n",
    "    # column alignment convertion from latex to markdown\n",
    "    col_align = {'l': u':--', 'c': u':-:', 'r': u'--:'}\n",
    "    \n",
    "    # if is a dataframe convert to the latex representation\n",
    "    if isinstance(df, pd.DataFrame):\n",
    "        table = df.to_latex(index=False)\n",
    "    else:\n",
    "        table = df\n",
    "    \n",
    "    # break by lines\n",
    "    table = table.split(u'\\n')\n",
    "    \n",
    "    # get the header formating\n",
    "    header = re.findall(u'\\\\\\\\begin{tabular}{([lcr]*)}', table[0])\n",
    "    # should find just one\n",
    "    header = header[0]\n",
    "    # convert from latex to markdown\n",
    "    header = [col_align[c] for c in header]\n",
    "    # put it together\n",
    "    header = u'|'.join(header) + u'\\\\\\\\'\n",
    "    # update the table\n",
    "    table[3] = header\n",
    "    # get rid of the extras at the top and bottom\n",
    "    table = table[2:-3]\n",
    "    # add '|' on the extremes and an \\n\n",
    "    table = [u'|{}|\\n'.format(re.sub(u' & ', u'|', t)[:-2]) for t in table]\n",
    "    table = u''.join(table)\n",
    "    \n",
    "    return table"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "columns = {'balance_amt': np.int64}\n",
    "\n",
    "df = pd.DataFrame({'balance_amt': np.array([1000*np.random.rand() for _ in range(500)])})\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tb = pd.DataFrame({'A': [i for i in range(65, 70)],\n",
    "                   'B': [chr(i) for i in range(65, 70)]})\n",
    "tb"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Problem\n",
    "- This is more related with LaTeX but even using `\"placement\": \"H\"` does not force the elements to apper in the proper sequence. This could be related to the processing of an unordered list or dictionary.\n",
    "- There is no `caption` for the table.\n",
    "\n",
    "## Trying to force a ToC\n",
    "### There should be a ToC\n",
    "- ToC is NOT present with the default style.\n",
    "- ToC IS present with the `-f latex_ipypublish_nocode`\n",
    "- The ToC should include tables\n",
    "- The ToC should include figures"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ipub": {
     "figure": {
      "placement": "H"
     },
     "mkdown": true,
     "table": {
      "placement": "H"
     }
    }
   },
   "outputs": [],
   "source": [
    "table_count = 1\n",
    "figure_count = 1\n",
    "\n",
    "for var in columns.keys():\n",
    "    var_l = re.sub('_', '\\_', var)\n",
    "    display(Markdown('#### Describe for %s  ' % var),\n",
    "            metadata={'ipub':{'mkdown': 'true'}})\n",
    "\n",
    "    display(Markdown(to_markdown(tb.to_latex(index=False))),\n",
    "                     metadata={'ipub':{'table':{'caption':'Describe for %s  ' % var_l,'label':'table:tlabel%d' % table_count,'placement':'H'}}})\n",
    "    table_count += 1\n",
    "    \n",
    "    # histograms\n",
    "    display(Markdown('#### Histograms for `%s`  ' % var),\n",
    "            metadata={'ipub':{'mkdown':{'placement':'H'}}})\n",
    "\n",
    "    mi, ma = df[var].min(), df[var].max()\n",
    "    bin = ma - mi\n",
    "    bin = 80 if bin > 80 else bin\n",
    "    fig = plt.figure(figsize=(15, 5))\n",
    "    plt.grid(zorder=0)\n",
    "    plt.hist(df[var], bins=bin, zorder=3)\n",
    "    plt.title('%s: Histogram between %d (min) and %d (max)' % (var, mi, ma), fontsize=14)\n",
    "    plt.close()\n",
    "    display(fig, \n",
    "            metadata={'ipub':{'figure':{'caption':'Describe for %s  ' % var_l,'label':'figure:flabel%d' % figure_count,'placement':'H'}}})\n",
    "    figure_count += 1"
   ]
  }
 ],
 "metadata": {
  "celltoolbar": "Edit Metadata",
  "ipub": {
   "titlepage": {
    "author": "Angelo Klin",
    "email": "angelo.klin@katra.com.au",
    "institution": [
     "Katra"
    ],
    "listcode": false,
    "listfigures": true,
    "listtables": true,
    "subtitle": "Queries",
    "supervisors": [
     "The Boss"
    ],
    "tagline": "Using data and technology to create products.",
    "title": "Data Quality",
    "toc": true
   }
  },
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by chrisjsewell** [comment]
Hey Angelo. So firstly I would advise having a look at the .tex file (in the converted folder) to see what is being outta it from ipypublish, before being passed to the latexmk. 

1. All outputs are in the correct order, but the issue is with the 4th level headers (####) which are represented in latex as \paragraph and which the figure placements don't appear to respect. Did a quick google search and couldn't find an answer why. If you don't use #### then ordering is fine
2. I also noted that they aren't being numbered, and so have updated the latex template with '\setcounter{secnumdepth}{5}'
3. Ipypublish isn't set (at present) to look for tables written in markdown. Is there a reason that you convert to markdown, given that it gets converted back to latex anyway (see the .tex file) before being converted to PDF?
4. Your toc isn't showing because you set the tag in the wrong place. It should be

'''
"ipub":{"toc":true}
'''

Not

'''
"ipub":{"titlepage":{"toc":true}}
'''

Ta,
Chris

**Comment by chrisjsewell** [comment]
To get list of figures and tables:

{
"ipub": {
  "toc": true,
  "listfigures": true,
  "listtables": true
  }
}

**Comment by angeloklin** [comment]
Hello Chris,
  Thanks again for your reply.
  - The .tex has the correct components in the correct order the time I checked, but I run so many times.
  - I was using `####` more to have it bold. I forgot to try a simpler **bold** option. I got caught on the order thing.
  - I am fine with the ToC having just 3 levels. Again the `####` was to have a visual break between some tables.
  - The first issues is that I want to remove the index of the pandas dataframe and the easy way out is to use `.to_latex`, funny enough it does not have a `.to_markdown`. THe other part is that I want it to be both on the notebook and on the latex/pdf export. I think it was not showing when using `.to_latex`. So my convoluted workaround was to use `.to_latex` to eliminate the index, and markdown to force it to be displayed. I tried both `raw=True/False`.
  - Thanks for spotting the misplace of the `toc/list*`. I will review that.

Thanks

**Comment by chrisjsewell** [comment]
Yes so this where the new info in the documentation comes into play :) This will remove the index and give you a nice display in both the notebook (in html) and in pdf (in latex)

from IPython.display import display
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random((3,3)))
latex = df.to_latex(index=False)
html = df.to_html(index=False)
display({'text/latex':latex,
         'text/html':html},raw=True, metadata={})

**Comment by angeloklin** [comment]
Thank you, Chris.
  All working.

  Kind of new topics (you can split and create new tickets if it is more complicated than one simple answer:
  1) The caption for tables comes before the table, and the caption for figures comes after the figures. Is that defined in the template/Jinja or is something that can be resolved with the `placement` option?
  2) If I want to use another package, say `wallpaper` or `background` or more generic, if I want to pass LaTeX code directly, is there a way? Trick part: packages go before the `\begin{document}` whilst `\newpage` comes after.

Aside from that, feel free to close it.

**Comment by chrisjsewell** [comment]
1. The caption placement is specifically implemented in https://github.com/chrisjsewell/ipypublish/blob/master/ipypublish/latex/ipypublish/contents_output.py. The rationale is summarised here: https://tex.stackexchange.com/questions/3243/why-should-a-table-caption-be-placed-above-the-table.
2. To add packages either add code directly to https://github.com/chrisjsewell/ipypublish/blob/master/ipypublish/latex/ipypublish/doc_article.py (at line 41) or, better, create a new plugin; based on the current ones but add a new template dict to `create_tplx` as descibed [here](https://github.com/chrisjsewell/ipypublish#creating-a-bespoke-converter). Or if there are any packages that you think it may be useful to specifically have in the core program, let me know.

Ta,
Chris

**Comment by angeloklin** [comment]
Hello Chris,
  Check the `front_pages.py`. There is a variable error in the loop for institutions. (Cut&Paste from supervisors).

**Comment by angeloklin** [comment]
Also,
  I made some modifications to add the `wallpaper` package to create a background image on the front page.
  I created new copies of the `front_pages.py` and `doc_article.py` and had to make a few changes in the `latex_doc_links.py`.
  I did create the `ipypublish_plugins` directory and a copy of `latex_ipypublish_nocode.py` but I could not figure how to put the new files in the same directory. Module references errors.
  My concern is that when I update `ipypublish` I will loose the changes, as I had to make changes in the code and could not isolate them in the user plugins directory.

**Comment by chrisjsewell** [comment]
> There is a variable error in the loop for institutions

I think this has already been fixed [here](https://github.com/chrisjsewell/ipypublish/commit/08ef5dcc07d60fe0b0a71847932cca8d9231b89b#diff-9a514ae824cfd216ac21b8fb89895b62L78)?

**Comment by chrisjsewell** [comment]
> I created new copies of the `front_pages.py` and `doc_article.py`

Can you specify what the changes are?

> and had to make a few changes in the `latex_doc_links.py`

And again with this, I presume this was related to having the image file copied to the correct place

**Comment by angeloklin** [comment]
Hello @chrisjsewell,

  I made this changes to be able to add a page size image as the background of the cover/title page. I used LaTeX package [wallpaper](https://www.ctan.org/pkg/wallpaper).

  1.a. Create a local/user plugin by copying `latex_ipypublish_nocode.py` to a local `./ipypublish_plugins/`

  1.b. Edit `latex_ipypublish_nocode.py` to point to personalised code:
```
#from ipypublish.latex.ipypublish import doc_article as doc
from ipypublish.latex.ipypublish import my_article as doc
# . . .
#from ipypublish.latex.ipypublish import front_pages as title
from ipypublish.latex.ipypublish import my_front_pages as title
```

  2.a. On `/Users/angeloklin/anaconda2/lib/python2.7/site-packages/ipypublish/latex/ipypublish/
`
```
cp -vp doc_article.py my_front_pages.py
cp -vp front_pages.py my_front_pages.py
```

  2.b. Edit `my_doc_article.py` to add package `wallpaper`
```
           \usepackage[footsepline=0.25pt]{scrlayer-scrpage}
+++        \usepackage{wallpaper}
```

  2.c. Edit `my_front_pages.py` to add code to manage `cover`
```
     ((*- if nb.metadata["ipub"]["titlepage"]: -*))
+++        ((*- if nb.metadata["ipub"]["titlepage"]["cover"]: -*))
+++        ((* set filename = nb.metadata.ipub.titlepage.cover | posix_path *))
+++        \ThisULCornerWallPaper{1}{((( filename )))}
+++        ((*- endif *))
           \begin{titlepage}

           ((*- if nb.metadata["ipub"]["titlepage"]["logo"]: -*))
```

  2.d. On `/Users/angeloklin/anaconda2/lib/python2.7/site-packages/ipypublish/preprocessors/
`

  2.e. Edit `latex_doc_links.py` to manage cover image file to be moved to `./converted/images`
```
               if hasattr(nb.metadata.ipub, 'titlepage'):
+++                if hasattr(nb.metadata.ipub.titlepage, 'cover'):
+++                    cover = nb.metadata.ipub.titlepage.cover
+++                    cover = self.resolve_path(cover, self.metapath)
+++                    if not os.path.exists(cover):
+++                        logging.warning('cover in metadata does not exist'
+++                                        ': {}'.format(cover))
+++                    else:
+++                        external_files.append(cover)
+++
+++                    nb.metadata.ipub.titlepage.cover = os.path.join(self.filesfolder,
+++                                                               os.path.basename(cover))

                   if hasattr(nb.metadata.ipub.titlepage, 'logo'):
```

  A suggestion for the documentation on the **creating your own...** is to give names to the files and where they should go. The examples assume some familiarity with Python.
  Still, on that topic, I could not find the proper syntax to have all my files in the `./ipypublish_plugins` using `from ... import`, which means if I upgrade from `v6.1` I will lose my changes or will have to remember to save and reapply.

Cheers

**Comment by chrisjsewell** [comment]
Hey Angelo, a background for the title page sounds like a nice addition, so I'll try and get round to putting it in the main code. Basically the same as your implementation but perhaps wrap \usepackage{wallpaper} in an `if` statement, such that it is only imported if it is going to be used. You could always try making your own [Pull Request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) to commit your code to the main ipypublish repo ;) 

Out of interest though, have you tried just using `import my_article as doc` or does that also not work?
