### ISSUE TITLE
Error with ipub:institution after update to version 0.6.2

### ISSUE THREAD

**Issue by gcpeixoto** [chrisjsewell/ipypublish#39]
@chrisjsewell, 

After updating to version 0.6.2, I have experienced an error that I did not have before: 

It looks like something was left misplaced in this release. I can assure that this has to do with the entry
```json
ipub: { 
"institution": "name",
}
```
but I have not hunted where the bug is. To me, each character of my institution name is now appearing written vertically (one below the other) and leaking out to the second page. My log file shows up lots of this:
```
INFO:pdfexport:latexmk: ! LaTeX Error: There's no line here to end.
INFO:pdfexport:latexmk:
INFO:pdfexport:latexmk: See the LaTeX manual or LaTeX Companion for explanation.
INFO:pdfexport:latexmk: Type  H <return>  for immediate help.
INFO:pdfexport:latexmk: ...
INFO:pdfexport:latexmk:
INFO:pdfexport:latexmk: l.447 ^^I^^I  \LARGE{ }\\
```

See screenshot below: 

<img width="318" alt="screen shot 2017-08-06 at 21 48 03" src="https://user-images.githubusercontent.com/1199443/29008648-f97be578-7af0-11e7-82c2-21e1c93171d4.png">

**Comment by chrisjsewell** [comment]
Hey gustavo, I'm suprised this worked before 0.6.2. As mentioned [here](https://github.com/chrisjsewell/ipypublish#document-tags), institution should be a list such that each element is on a new line, e.g.

ipub: { 
"titlepage":{
"institution": ["name","department"]
}
}

without the [ and ], it is treating each individual character in the string as an item. Let me know if this solves the issue

**Comment by gcpeixoto** [comment]
Hi! Got it! A mistake... It works now. 👍
