### ISSUE TITLE
Resolution of multiple tags (e.g. table=true and equation=true)

### ISSUE THREAD

**Issue by gcpeixoto** [chrisjsewell/ipypublish#41]
@chrisjsewell, 

Another error I have been experiencing with the new release (on a guess base) is related to Latex-renderized outputs. In some cells, I print symbolic expressions with the fancier output brought me by Sympy's `init_printing()` function. 

So far, this was running smoothly, but now, not only the expressions are being printed wrongly, but also a bunch of errors are being launched like this excerpt: 

```
INFO:pdfexport:latexmk: ! Missing $ inserted.
INFO:pdfexport:latexmk: <inserted text>
INFO:pdfexport:latexmk: $
INFO:pdfexport:latexmk: l.1536 ...ght)^{2} \left(x_{0} - x_{2}\right)^{2}}
INFO:pdfexport:latexmk: + \frac{1.0 dy_{1} \left(...
INFO:pdfexport:latexmk: 
INFO:pdfexport:latexmk: ? ! Missing $ inserted.
INFO:pdfexport:latexmk: <inserted text>
INFO:pdfexport:latexmk: $
INFO:pdfexport:latexmk: l.1536 ...ght)^{2} \left(x_{0} - x_{2}\right)^{2}}
INFO:pdfexport:latexmk: + \frac{1.0 dy_{1} \left(...
INFO:pdfexport:latexmk: 
INFO:pdfexport:latexmk: ? ! Missing $ inserted.
INFO:pdfexport:latexmk: <inserted text>
INFO:pdfexport:latexmk: $
INFO:pdfexport:latexmk: l.1536 ...ght)^{2} \left(x_{0} - x_{2}\right)^{2}}
INFO:pdfexport:latexmk: + \frac{1.0 dy_{1} \left(...
INFO:pdfexport:latexmk: 
INFO:pdfexport:latexmk: ? ! Extra }, or forgotten $.
INFO:pdfexport:latexmk: \frac  #1#2->{\begingroup #1\endgroup \@@over #2}
INFO:pdfexport:latexmk: 
INFO:pdfexport:latexmk: l.1536 ...ght)^{2} \left(x_{0} - x_{2}\right)^{2}}
INFO:pdfexport:latexmk: + \frac{1.0 dy_{1} \left(...
```

The expressions are a bit long, in fact, but they do not match on the .ipynb and the .pdf produced compiled with `ipypublish_all` flag. Below, two SSs for comparison: 

*.ipynb*
<img width="1029" alt="screen shot 2017-08-06 at 22 10 00" src="https://user-images.githubusercontent.com/1199443/29008880-2656bf66-7af4-11e7-9248-cbf53e5484ff.png">

*.pdf*
<img width="840" alt="screen shot 2017-08-06 at 21 58 49" src="https://user-images.githubusercontent.com/1199443/29008887-47c02ebc-7af4-11e7-8ef3-612764a6d8e5.png">

Some clue about this one?

**Comment by chrisjsewell** [comment]
Hmm sound like something to do with removing the $ wrappings. Could you also show me what it looks like:

1. in the .ipynb when you open it as a text file. You should be searching for something like this:
```json
      "text/latex": [
       "$$\\frac{...}{...}+...$$"
      ],
```
2. in the .tex file

**Comment by chrisjsewell** [comment]
As I mention above it would be helpful to look at your .tex file to confirm this.

But what I believe is occurring is that, because in `ipypublish_all` it sets both `equation=true` and `table=true` in the metadata tags, the equation text/latex is mistakenly being placed in a table environment.

**Comment by chrisjsewell** [comment]
if you try v.0.6.3 this should, hopefully, be fixed.

Additionally, latex doesn't inherently wrap the equations, like you see in the notebook. But if you try putting this in the cell metadata, it should do the job:

```json
{
  "ipub": {
	  "equation": {
        "environment": "breqn"
	  }
   }
}
```

This is also now detailed in the documentation: https://github.com/chrisjsewell/ipypublish#cell-tags

**Comment by chrisjsewell** [comment]
closing this, as I believe it to be fixed. But feel free to reopen if you have further issues :)
