### ISSUE TITLE
Support raw cells

### ISSUE THREAD

**Issue by andreas-zeller** [chrisjsewell/ipypublish#49]
First of all, thanks for a great tool!  I am currently using ipypublish for writing a textbook on "generating software tests."

One issue: nbpublish does not seem to support raw cells in documents, as nbconvert does.  Sometimes, I'd like to include content that is LaTeX-only or HTML-only, which I'd put into raw cells; but nbpublish seems to ignore all "raw" content.

**Comment by chrisjsewell** [comment]
Hey thanks for the feedback, would love to see the book when its done :)
Hopefully I've just fixed this with the latest version (0.6.7), let me know if that works for you ta

**Comment by chrisjsewell** [comment]
It's been a while, so assuming I can close this
