### ISSUE TITLE
nbpublish and nbpresent scripts not found on Windows

### ISSUE THREAD

**Issue by stefanuddenberg** [chrisjsewell/ipypublish#52]
I needed to manually add "nbpublish.bat" and "nbpresent.bat" files to my "anaconda3\Scripts\" folder to get the command line tools of the same names to be recognized. They consisted of the following code:

`python.exe %~dp0nbpublish %*`
and
`python.exe %~dp0nbpresent %*`

Should be simple to implement this on installation.

**Comment by chrisjsewell** [comment]
Thanks, would of thought this should be something that pip handled, but I tend to stay away from Windows

**Comment by chrisjsewell** [comment]
I guess this is the answer: https://stackoverflow.com/questions/35566376/how-to-use-setuptools-to-install-a-python-script-for-windows-command-line
