### ISSUE TITLE
Headings and code fonts are pixelated in converted pdf

### ISSUE THREAD

**Issue by stefanuddenberg** [chrisjsewell/ipypublish#54]
It's unclear to me why this problem is specific to headings and code snippets. It is completely absent for body text.

# Heading:
![image](https://user-images.githubusercontent.com/32106244/49998986-aa5f0800-ff63-11e8-96fd-b50e6b314763.png)

# Body text:
![image](https://user-images.githubusercontent.com/32106244/49999028-c6fb4000-ff63-11e8-9d5c-90b54a75ecd2.png)

# Code snippet
![image](https://user-images.githubusercontent.com/32106244/49999058-d7abb600-ff63-11e8-9afe-577053af30e3.png)

**Comment by stefanuddenberg** [comment]
Solution: https://tex.stackexchange.com/questions/205578/the-text-in-pdf-is-not-smooth

**Comment by chrisjsewell** [comment]
Always good when people solve there own issues :)
