### ISSUE TITLE
Allow use of different citation styles

### ISSUE THREAD

**Issue by stefanuddenberg** [chrisjsewell/ipypublish#58]
It isn't clear to me from the documentation how one would go about using, say, APA style with ipypublish. Is there a simple way to feed in a .csl file?

**Comment by stefanuddenberg** [comment]
It's also worth pointing out that the default citation style is incomplete, since it doesn't include the journal or year of publication. This is despite direct copying from Zotero, as in the example workflow GIF.

**Comment by chrisjsewell** [comment]
Hey @stefanuddenberg  I got you email thanks 👍 was just waiting to put out the new version of ipypublish (v0.7.0) before responding, see the main changes [here](https://ipypublish.readthedocs.io/en/latest/custom_export_config.html#custom-export-configurations).

So essentially [this file](https://ipypublish.readthedocs.io/en/latest/segment_example.html) is responsible for inserting the LaTeX, for creating the bibliography, into the template. It uses natbib and, as explained [here](https://ipypublish.readthedocs.io/en/latest/metadata_tags.html#bibliography), I have added an extra option to control the style of the bibliography. 

It would also be easy to replace this file, in the export configuration, with one that uses [BibLaTex](https://www.overleaf.com/learn/latex/Articles/Getting_started_with_BibLaTeX), which allows for even greater control over how the bibliography looks, and an extended range of out the box [citation styles](https://www.overleaf.com/learn/latex/Biblatex_citation_styles).

In terms of .csl files, from a quick Google, it doesn't seem that there is an easy solution for use with LaTeX, Here's a [comparison of CSL and BibLateX](https://tex.stackexchange.com/questions/434946/citation-style-language-vs-biblatex-vs-possibly-other-citing-systems/435004)

Let us know how that works for you

**Comment by stefanuddenberg** [comment]
Thank you so much! I actually spent a while figuring out how the previous
version works and finally got it working with APA style. This update looks
huge; thank you for all your help!

Best,
Stefan

**Comment by chrisjsewell** [comment]
Thanks! How did you implement the APA style? 
Basically I think this should work for biblatex:

```json
{
  "$schema": "../outline_schema/latex_tplx_schema.json",
  "identifier": "ipypublish-biblio_biblatex",
  "description": "with the main ipypublish bibliography",
  "segments": {
    "document_packages": [
      "",
      "% bibliography formatting",
      "\\usepackage[backend=bibtex, bibencoding=ascii,style=numeric-comp,",
      "sorting=none, firstinits=true, url=false,isbn=false ]{biblatex}",
      "% hyperlink doi's",
      "\\usepackage{doi}"
    ],
    "document_header_end": [
      "((*- if nb.metadata.ipub: -*))",
      "((*- if nb.metadata.ipub.bibliography: -*))",
      "((* set filename = nb.metadata.ipub.bibliography | strip_ext | posix_path *))",
      "\\addbibresource{((( filename )))}",
      "((*- endif *))",
      "((*- endif *))"
    ],
    "document_bibliography": [
      "",
      "((*- if nb.metadata.ipub: -*))",
      "((*- if nb.metadata.ipub.bibliography: -*))",
      "\\printbibliography[heading=bibintoc, title={Bibliography}]",
      "((*- endif *))",
      "((*- endif *))"
    ]
  },
  "template": "latex-tplx"
}
```

Definitely let me know how you get on, and hopefully can get your presentation on the [website](https://ipypublish.readthedocs.io/en/latest/applications.html)!

**Comment by stefanuddenberg** [comment]
I modified `biblio_natbib.py` as follows, and used .bib files generated in Better BibTex format with url, urldate, and month information suppressed from the bib file. 

```python
tplx_dict = {
    "meta_docstring": "with the main ipypublish bibliography",
    "document_packages": r"""
	% bibliography formatting
	\usepackage[natbibapa, nodoi]{apacite} % formerly natbib
	% hyperlink doi's
	\usepackage{doi}
""",
    "document_bibliography": r"""
((*- if nb.metadata.ipub: -*))
((*- if nb.metadata.ipub.bibliography: -*))
((* set filename = nb.metadata.ipub.bibliography | posix_path *))

% sort citations by order of first appearance
\bibliographystyle{apacite} % formerly unsrtnat
\bibliography{((( filename )))}

((*- endif *))
((*- endif *))
""",
}
```

**Comment by chrisjsewell** [comment]
When you get a chance, if you could let me know that this all still works for you with v0.7.0 ta

**Comment by chrisjsewell** [comment]
I'm including this here for future reference: 

- https://tex.stackexchange.com/questions/263793/what-is-the-relationship-between-natbib-apacite-package-and-apa-document-class
- https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib/25702#25702

**Comment by chrisjsewell** [comment]
moved to #61
