### ISSUE TITLE
Latex errors if figure labels include underscores

### ISSUE THREAD

**Issue by claresloggett** [chrisjsewell/ipypublish#65]
I think this issue is a bug with an easy workaround, and probably is a latex issue at heart. However it cost me a lot of pain to discover what the problem was, so it would be good to at least document it if that's not done already.

As recommended in the documentation, I'm importing 

```from ipypublish.scripts.ipynb_latex_setup import *```

at the top of my Jupyter Notebook. 

If I create a plot where the figure labels contain underscores, then run the notebook cell, the figure fails to render and I get latex errors like:

```
RuntimeError: latex was not able to process the following string:
b'y_values'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/Users/clare/.matplotlib/tex.cache/7fe104e47212b624ca12a6d46285698e.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 22 language(s) loaded.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/ts1enc.def
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/subdepth/subdepth.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2018basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file 7fe104e47212b624ca12a6d46285698e.aux.
(/usr/local/texlive/2018basic/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Missing $ inserted.
<inserted text> 
                $
l.15 \fontsize{18.000000}{22.500000}{\rmfamily y_
                                                 values}
No pages of output.
Transcript written on 7fe104e47212b624ca12a6d46285698e.log.
```

The actual stack trace is a lot longer due to the layers of processing going on here - I can post it if appropriate.

For instance, the following code snippet triggers this error due to the y-axis label (take the underscore out of the label and it's fine):

```
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,4,9,16])
plt.ylabel('y_values')
```

The following Pandas/Seaborn code snippet triggers the error due to the y-axis tick labels containing underscores:

```
import seaborn as sns
import pandas as pd
sns.boxenplot(
    data=pd.DataFrame(dict(y=['a_1']*3 + ['a_2']*3, x=[1,2,3,5,6,7])),
    x='x',
    y='y')
```

This second example is analogous to the issue I actually ran into: categorical label names in my dataset, and therefore values in my DataFrame, contained underscores. 

This issue is pretty hard for the user to diagnose if you're rusty with Latex. The error message does indicate that the string "a_1" (or whatever) is the issue, but it's nested in a stack trace of Python errors and comes with a bunch of Latex complaints about height and width. I at first thought my labels were too long and my figure was just too wide to render.

**Comment by chrisjsewell** [comment]
Hey clare, yes thanks for highlighting this,  I've had this issue before; `_` need to be escaped by `\`, i.e. `\_`, I guess its more of a bug with matplotlib/pandas, that they should handle, but it definitely would be helpful to at least add a note on it in the ipypublish documentation.

Could I be cheeky, and close this issue, and ask you to rewrite it in the issue template I've just created (if you click on New Issue you'll now be given the option of a bug report)

**Comment by claresloggett** [comment]
Sure, https://github.com/chrisjsewell/ipypublish/issues/66

Sounds like this issue should be moved to matplotlib?
