### ISSUE TITLE
tornado < 6

### ISSUE THREAD

**Issue by danieltomasz** [chrisjsewell/ipypublish#71]
# Bug Report
ipypublish 0.9.4 has requirement tornado<6, but you'll have tornado 6.0.1 which is incompatible.

## Describe the bug

Is there a reason to holding to previous tornado version?

**Comment by danieltomasz** [comment]
Sorry for putting it as a bug report, I cannot edit now :(

**Comment by chrisjsewell** [comment]
Hey Dan, it was due to this issue jupyter/nbconvert#894, which they appear to have recently fixed.
So I basically need to copy their fix into ipypublish/postprocessors/reveal_serve.py
