### ISSUE TITLE
list supported python versions

### ISSUE THREAD

**Issue by danieltomasz** [chrisjsewell/ipypublish#72]
**Is your feature request related to a problem? Please describe.**
There is no information about what versions of python are supported and tested, especially python 3.3 and Python 3.4. Many other packages from which `pypublish`  is depending already dropped support for Python `3.4' .

**Describe the solution you'd like**
There would be nice to put this info into Readme as a badge.

**Comment by chrisjsewell** [comment]
I think you need to have another look lol, If you click on the ``build`` badge on the readme (and first page of the docs), it will take you to
[the CI tests](https://travis-ci.org/chrisjsewell/ipypublish), which you'll see are currently
passing for 2.7, 3.4, 3.5 and 3.6
